# Generated by Django 4.2.30 on 2026-08-02 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='MANUAL', max_length=50)),
                ('external_profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('current_role', models.CharField(blank=True, max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='USER_ENTERED', max_length=50)),
                ('sync_status', models.CharField(default='IDLE', max_length=50)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('target_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('completeness_score', models.IntegerField(default=0)),
                ('evidence_alignment_score', models.IntegerField(default=0)),
                ('keyword_alignment_score', models.IntegerField(default=0)),
                ('consistency_score', models.IntegerField(default=0)),
                ('recruiter_readiness_score', models.IntegerField(default=0)),
                ('analysis_version', models.CharField(default='1.0', max_length=50)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='career_brand.professionalprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(blank=True, max_length=255)),
                ('target_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('structured_content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='career_brand.professionalprofile')),
                ('source_analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_brand.professionalprofileanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_versions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('HEADLINE', 'Headline'), ('ABOUT', 'About'), ('EXPERIENCE', 'Experience'), ('PROJECT', 'Project'), ('SKILL', 'Skill'), ('EDUCATION', 'Education'), ('CERTIFICATION', 'Certification'), ('VOLUNTEERING', 'Volunteering'), ('AWARD', 'Award'), ('PUBLICATION', 'Publication'), ('OTHER', 'Other')], max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('raw_content', models.TextField(blank=True)),
                ('structured_content', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='USER_ENTERED', max_length=50)),
                ('verification_status', models.CharField(default='UNVERIFIED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='career_brand.professionalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfileRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(blank=True, choices=[('HEADLINE', 'Headline'), ('ABOUT', 'About'), ('EXPERIENCE', 'Experience'), ('PROJECT', 'Project'), ('SKILL', 'Skill'), ('EDUCATION', 'Education'), ('CERTIFICATION', 'Certification'), ('VOLUNTEERING', 'Volunteering'), ('AWARD', 'Award'), ('PUBLICATION', 'Publication'), ('OTHER', 'Other')], max_length=50)),
                ('recommendation_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('reason_code', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('current_text', models.TextField(blank=True)),
                ('proposed_text', models.TextField(blank=True)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='career_brand.professionalprofileanalysis')),
            ],
        ),
    ]
