# Generated by Django 4.2.30 on 2026-08-09 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_decisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerExecutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_type', models.CharField(max_length=50)),
                ('source_phase', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('BLOCKED', 'Blocked'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_USER', 'Waiting For User'), ('WAITING_FOR_SYSTEM', 'Waiting For System'), ('REVIEW_REQUIRED', 'Review Required'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=50)),
                ('execution_mode', models.CharField(choices=[('USER_ACTION', 'User Action'), ('ASSISTED', 'Assisted'), ('REVIEW_REQUIRED', 'Review Required'), ('AUTO_EXECUTABLE', 'Auto Executable'), ('SYSTEM_OBSERVATION', 'System Observation'), ('BLOCKED', 'Blocked')], default='USER_ACTION', max_length=50)),
                ('impact_score', models.IntegerField(default=0)),
                ('urgency_score', models.IntegerField(default=0)),
                ('effort_penalty', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerExecutionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('skill_score', models.IntegerField(default=0)),
                ('evidence_score', models.IntegerField(default=0)),
                ('brand_score', models.IntegerField(default=0)),
                ('interview_score', models.IntegerField(default=0)),
                ('application_score', models.IntegerField(default=0)),
                ('pathway_score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_progress_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerExecutionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_execution_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerExecutionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('USER_COMPLETED', 'User Completed'), ('SYSTEM_COMPLETED', 'System Completed'), ('BLOCKED', 'Blocked'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown'), ('SUPERSEDED', 'Superseded')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='career_execution.careerexecutionitem')),
            ],
        ),
        migrations.AddField(
            model_name='careerexecutionitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='career_execution.careerexecutionplan'),
        ),
        migrations.AddField(
            model_name='careerexecutionitem',
            name='source_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_items', to='career_decisions.careeraction'),
        ),
        migrations.CreateModel(
            name='CareerExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_execution.careerexecutionitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerExecutionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_items', to='career_execution.careerexecutionitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='career_execution.careerexecutionitem')),
            ],
            options={
                'unique_together': {('item', 'depends_on')},
            },
        ),
    ]
