# Generated by Django 4.2.30 on 2026-08-09 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDecisionPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_snapshot_hash', models.CharField(help_text='Hash to detect staleness', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_decision_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SKILL_GAP', 'Skill Gap'), ('EVIDENCE_GAP', 'Evidence Gap'), ('INTERVIEW_GAP', 'Interview Gap'), ('CAREER_BRAND_GAP', 'Career Brand Gap'), ('APPLICATION_STRATEGY', 'Application Strategy'), ('JOB_MARKET_ALIGNMENT', 'Job Market Alignment'), ('WORK_AUTHORIZATION', 'Work Authorization'), ('SPONSORSHIP', 'Sponsorship'), ('COMPENSATION_ALIGNMENT', 'Compensation Alignment'), ('APPLICATION_CONVERSION', 'Application Conversion'), ('TARGET_ROLE_MISMATCH', 'Target Role Mismatch')], max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('impact_score', models.IntegerField(help_text='Deterministic 0-100 score')),
                ('urgency', models.IntegerField(help_text='0-100 scale')),
                ('confidence', models.IntegerField(help_text='0-100 scale based on data volume')),
                ('explanation', models.TextField()),
                ('evidence_references', models.JSONField(default=list)),
                ('recommended_action', models.CharField(max_length=255)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='career_decisions.careerdecisionplanversion')),
            ],
            options={
                'ordering': ['-impact_score'],
            },
        ),
        migrations.CreateModel(
            name='CareerDecisionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Immutable snapshot of the inputs used (skills, readiness, market, pathways).')),
                ('plan_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='career_decisions.careerdecisionplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='CareerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_type', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('USER_ACTION_REQUIRED', 'User Action Required'), ('PREPARE', 'Prepare'), ('REVIEW_REQUIRED', 'Review Required'), ('AUTO_EXECUTABLE', 'Auto Executable'), ('BLOCKED', 'Blocked')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('source_phase', models.CharField(max_length=50)),
                ('impact_score', models.IntegerField(default=0)),
                ('urgency_score', models.IntegerField(default=0)),
                ('effort_penalty', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('evidence_references', models.JSONField(default=list)),
                ('target_role', models.CharField(blank=True, max_length=100)),
                ('target_country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='career_decisions.careerdecisionplanversion')),
            ],
        ),
        migrations.CreateModel(
            name='CareerActionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='career_decisions.careeraction')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_actions', to='career_decisions.careeraction')),
            ],
            options={
                'unique_together': {('action', 'depends_on')},
            },
        ),
    ]
