# Generated by Django 4.2.30 on 2026-08-09 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOutcomeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APPLICATION_SUBMITTED', 'Application Submitted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('APPLICATION_INTERVIEW', 'Application Interview'), ('APPLICATION_FINAL_ROUND', 'Application Final Round'), ('APPLICATION_OFFER', 'Application Offer'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('INTERVIEW_WEAKNESS_IDENTIFIED', 'Interview Weakness Identified'), ('SKILL_VERIFIED', 'Skill Verified'), ('SKILL_GAP_CLOSED', 'Skill Gap Closed'), ('EVIDENCE_VERIFIED', 'Evidence Verified'), ('CAREER_BRAND_UPDATED', 'Career Brand Updated'), ('CAREER_DECISION_CHANGED', 'Career Decision Changed'), ('CAREER_EXECUTION_COMPLETED', 'Career Execution Completed')], max_length=100)),
                ('source_domain', models.CharField(choices=[('CONTEXT', 'Candidate Context'), ('SKILL_GAP', 'Skill Gap'), ('LEARNING', 'Learning Roadmap'), ('EVIDENCE', 'Evidence'), ('BRAND', 'Career Brand'), ('INTERVIEW', 'Interview Intelligence'), ('PATHWAY', 'Career Pathway'), ('DECISION', 'Career Decision'), ('EXECUTION', 'Career Execution'), ('ANALYTICS', 'Application Analytics')], max_length=50)),
                ('source_object_id', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains_marked_stale', models.JSONField(default=list)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='career_integration.careeroutcomeevent')),
            ],
        ),
        migrations.CreateModel(
            name='CareerOperatingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_readiness_score', models.IntegerField(default=0)),
                ('current_primary_goal', models.CharField(blank=True, max_length=255)),
                ('top_blocker', models.CharField(blank=True, max_length=255)),
                ('execution_velocity_score', models.IntegerField(default=0)),
                ('application_momentum_score', models.IntegerField(default=0)),
                ('overall_health', models.CharField(choices=[('HEALTHY', 'Healthy'), ('STALE', 'Stale'), ('DEGRADED', 'Degraded'), ('BLOCKED', 'Blocked'), ('ACTION_REQUIRED', 'Action Required'), ('AWAITING_USER', 'Awaiting User'), ('AI_UNAVAILABLE', 'AI Unavailable'), ('AUTOMATION_UNAVAILABLE', 'Automation Unavailable'), ('DATA_INCOMPLETE', 'Data Incomplete'), ('NOT_INITIALIZED', 'Not Initialized')], default='NOT_INITIALIZED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operating_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerIntegrationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=255)),
                ('trust_level_map', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareerDomainState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(choices=[('CONTEXT', 'Candidate Context'), ('SKILL_GAP', 'Skill Gap'), ('LEARNING', 'Learning Roadmap'), ('EVIDENCE', 'Evidence'), ('BRAND', 'Career Brand'), ('INTERVIEW', 'Interview Intelligence'), ('PATHWAY', 'Career Pathway'), ('DECISION', 'Career Decision'), ('EXECUTION', 'Career Execution'), ('ANALYTICS', 'Application Analytics')], max_length=50)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('STALE', 'Stale'), ('DEGRADED', 'Degraded'), ('BLOCKED', 'Blocked'), ('ACTION_REQUIRED', 'Action Required'), ('AWAITING_USER', 'Awaiting User'), ('AI_UNAVAILABLE', 'AI Unavailable'), ('AUTOMATION_UNAVAILABLE', 'Automation Unavailable'), ('DATA_INCOMPLETE', 'Data Incomplete'), ('NOT_INITIALIZED', 'Not Initialized')], default='NOT_INITIALIZED', max_length=50)),
                ('source_version_hash', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now_add=True)),
                ('operating_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='career_integration.careeroperatingstate')),
            ],
            options={
                'unique_together': {('operating_state', 'domain_name')},
            },
        ),
    ]
