# Generated by Django 4.2.30 on 2026-08-10 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('career_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careeroperatingstate',
            name='current_os_state',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('PROFILE_READY', 'Profile Ready'), ('JOB_SEARCH_READY', 'Job Search Ready'), ('MATCHING', 'Matching'), ('GAP_ANALYSIS', 'Gap Analysis'), ('LEARNING', 'Learning'), ('EVIDENCE_COLLECTION', 'Evidence Collection'), ('CAREER_BRAND_READY', 'Career Brand Ready'), ('INTERVIEW_PREPARATION', 'Interview Preparation'), ('PATHWAY_EXPLORATION', 'Pathway Exploration'), ('DECISION_READY', 'Decision Ready'), ('EXECUTION_READY', 'Execution Ready'), ('APPLICATION_ACTIVE', 'Application Active'), ('OUTCOME_TRACKING', 'Outcome Tracking'), ('OPTIMIZATION', 'Optimization'), ('BLOCKED', 'Blocked'), ('ACTION_REQUIRED', 'Action Required'), ('DEGRADED', 'Degraded')], default='ONBOARDING', max_length=50),
        ),
        migrations.CreateModel(
            name='UserActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_domain', models.CharField(choices=[('CONTEXT', 'Candidate Context'), ('SKILL_GAP', 'Skill Gap'), ('LEARNING', 'Learning Roadmap'), ('EVIDENCE', 'Evidence'), ('BRAND', 'Career Brand'), ('INTERVIEW', 'Interview Intelligence'), ('PATHWAY', 'Career Pathway'), ('DECISION', 'Career Decision'), ('EXECUTION', 'Career Execution'), ('ANALYTICS', 'Application Analytics')], max_length=50)),
                ('blocker_type', models.CharField(choices=[('MISSING_VERIFIED_SKILL', 'Missing Verified Skill'), ('MISSING_EVIDENCE', 'Missing Evidence'), ('RESUME_INCOMPLETE', 'Resume Incomplete'), ('PROFILE_INCONSISTENT', 'Profile Inconsistent'), ('INTERVIEW_GAP', 'Interview Gap'), ('APPLICATION_DATA_MISSING', 'Application Data Missing'), ('AUTHENTICATION_REQUIRED', 'Authentication Required'), ('CONSENT_REQUIRED', 'Consent Required'), ('CAPTCHA_REQUIRED', 'CAPTCHA Required'), ('USER_ACTION_REQUIRED', 'User Action Required'), ('ENTITLEMENT_BLOCKED', 'Entitlement Blocked'), ('PROVIDER_UNSUPPORTED', 'Provider Unsupported'), ('GLOBAL_PAUSE', 'Global Pause'), ('SYSTEM_DEGRADED', 'System Degraded'), ('STALE_DOMAIN', 'Stale Domain')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('context_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
