# Generated by Django 4.2.30 on 2026-08-09 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_role_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('target_role', models.CharField(max_length=150)),
                ('role_family', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('target_country', models.CharField(blank=True, max_length=10)),
                ('target_region', models.CharField(blank=True, max_length=150)),
                ('work_mode', models.CharField(blank=True, max_length=50)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPathScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=150)),
                ('target_country', models.CharField(blank=True, max_length=10)),
                ('target_region', models.CharField(blank=True, max_length=150)),
                ('work_mode', models.CharField(blank=True, max_length=50)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('baseline_snapshot', models.JSONField(default=dict)),
                ('simulated_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIMULATED', 'Simulated'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career_pathways.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_type', models.CharField(choices=[('SKILL', 'Skill'), ('LEARNING', 'Learning'), ('EXPERIENCE', 'Experience'), ('EVIDENCE', 'Evidence'), ('MARKET', 'Market'), ('LOCATION', 'Location'), ('WORK_AUTHORIZATION', 'Work Authorization'), ('INTERVIEW', 'Interview'), ('CAREER_BRAND', 'Career Brand')], max_length=50)),
                ('structured_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='career_pathways.careerpathscenario')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPathRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_skill', models.CharField(db_index=True, max_length=150)),
                ('skill_category', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('min_experience_months', models.IntegerField(default=0)),
                ('market_demand_reference', models.CharField(blank=True, max_length=255)),
                ('provenance', models.CharField(blank=True, max_length=100)),
                ('requirement_source', models.CharField(blank=True, max_length=150)),
                ('confidence_classification', models.CharField(blank=True, max_length=50)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='career_pathways.careerpath')),
            ],
        ),
    ]
