# Generated by Django 4.2.30 on 2026-08-02 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_job_canonical_hash_jobsourceoccurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_skill', models.CharField(db_index=True, max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=150)),
                ('resource_type', models.CharField(choices=[('DOCUMENTATION', 'Documentation'), ('COURSE', 'Course'), ('VIDEO', 'Video'), ('BOOK', 'Book'), ('PRACTICE', 'Practice'), ('CERTIFICATION', 'Certification'), ('LAB', 'Lab')], max_length=50)),
                ('url', models.URLField(max_length=500)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('estimated_duration_hours', models.FloatField(blank=True, null=True)),
                ('cost_type', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('FREEMIUM', 'Freemium'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('country_availability', models.JSONField(default=list)),
                ('verification_status', models.CharField(default='VERIFIED', max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hours_per_week', models.IntegerField(default=10)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('stale_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('SPECIFIC_JOB', 'Specific Job'), ('TARGET_ROLE', 'Target Role'), ('MARKET_AGGREGATE', 'Market Aggregate')], max_length=50)),
                ('target_role', models.CharField(blank=True, max_length=150)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('work_mode', models.CharField(blank=True, max_length=50)),
                ('candidate_context_snapshot', models.JSONField(default=dict)),
                ('requirement_snapshot', models.JSONField(default=dict)),
                ('market_sample_size', models.IntegerField(default=0)),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_analyses', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skill Gap Analyses',
            },
        ),
        migrations.CreateModel(
            name='SkillTaxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Taxonomies',
            },
        ),
        migrations.CreateModel(
            name='SkillGapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_skill', models.CharField(max_length=150)),
                ('candidate_state', models.CharField(max_length=50)),
                ('requirement_state', models.CharField(max_length=50)),
                ('gap_type', models.CharField(choices=[('NO_GAP', 'No Gap'), ('PROFICIENCY_GAP', 'Proficiency Gap'), ('EXPERIENCE_GAP', 'Experience Gap'), ('MISSING_SKILL', 'Missing Skill'), ('EVIDENCE_GAP', 'Evidence Gap')], max_length=50)),
                ('priority_score', models.FloatField(default=0.0)),
                ('priority_band', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_items', to='learning.skillgapanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='learning.skilltaxonomy')),
            ],
            options={
                'verbose_name_plural': 'Skill Aliases',
            },
        ),
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('target_skills', models.JSONField(default=list)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=50)),
                ('estimated_effort_hours', models.FloatField(blank=True, null=True)),
                ('deliverables', models.JSONField(default=list)),
                ('success_criteria', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='RECOMMENDED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to='learning.skillgapanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketSkillDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=150)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('canonical_skill', models.CharField(max_length=150)),
                ('sample_size', models.IntegerField(default=0)),
                ('required_frequency', models.FloatField(default=0.0)),
                ('preferred_frequency', models.FloatField(default=0.0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('target_role', 'country_code', 'experience_level', 'canonical_skill')},
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_skill', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50)),
                ('sequence', models.IntegerField(default=1)),
                ('estimated_effort_hours', models.FloatField(blank=True, null=True)),
                ('dependency_skills', models.JSONField(default=list)),
                ('completion_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked'), ('SKIPPED', 'Skipped')], default='NOT_STARTED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.learningroadmap')),
            ],
        ),
        migrations.AddField(
            model_name='learningroadmap',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='learning.skillgapanalysis'),
        ),
        migrations.AddField(
            model_name='learningroadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL),
        ),
    ]
