# Generated by Django 4.2.30 on 2026-08-01 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_job_canonical_hash_jobsourceoccurrence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0006_formsession_provider_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApplyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('trigger', models.CharField(default='SCHEDULED', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_discovered', models.IntegerField(default=0)),
                ('jobs_evaluated', models.IntegerField(default=0)),
                ('jobs_matched', models.IntegerField(default=0)),
                ('applications_created', models.IntegerField(default=0)),
                ('applications_prepared', models.IntegerField(default=0)),
                ('applications_executed', models.IntegerField(default=0)),
                ('applications_submitted', models.IntegerField(default=0)),
                ('applications_user_action_required', models.IntegerField(default=0)),
                ('applications_blocked', models.IntegerField(default=0)),
                ('applications_failed', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActionRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_required', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoApplyRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=50)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('execution_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='automation.autoapplyrun')),
            ],
        ),
        migrations.CreateModel(
            name='AutoApplyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_apply_enabled', models.BooleanField(default=False)),
                ('daily_application_limit', models.IntegerField(blank=True, null=True)),
                ('weekly_application_limit', models.IntegerField(blank=True, null=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('excluded_roles', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('minimum_salary', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('require_tailored_resume', models.BooleanField(default=True)),
                ('allow_unknown_salary', models.BooleanField(default=False)),
                ('allow_unknown_company', models.BooleanField(default=False)),
                ('allow_external_ats', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
