# Generated by Django 4.2.30 on 2026-08-10 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_autoapplyrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoapplyrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoapplyrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
