# Generated by Django 4.2.30 on 2026-08-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0002_resumeversion_alter_resume_ats_score_and_more'),
        ('jobs', '0004_remove_job_portal_type_job_application_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='Custom', max_length=100)),
                ('application_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('application_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('snapshot', models.JSONField(blank=True, help_text='Immutable snapshot of Job, ResumeVersion, and CandidateContext at submission', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('REVIEW_REQUIRED', 'Review Required'), ('READY_TO_SUBMIT', 'Ready to Submit'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('APPLICATION_FAILED', 'Application Failed'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('FINAL_ROUND', 'Final Round'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('UNKNOWN', 'Unknown'), ('Saved', 'Saved'), ('Applied', 'Applied')], default='DRAFT', max_length=30)),
                ('preparation_status', models.CharField(blank=True, max_length=30, null=True)),
                ('submission_status', models.CharField(blank=True, max_length=30, null=True)),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('external_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('match_score', models.IntegerField(default=0)),
                ('match_details', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_change_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.job')),
                ('resume_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField()),
                ('location_type', models.CharField(default='Virtual', max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
                ('source_field_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_source', models.CharField(blank=True, max_length=50, null=True)),
                ('review_status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('canonical_category', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField()),
                ('answer_type', models.CharField(default='TEXT', max_length=50)),
                ('source', models.CharField(default='USER_ENTERED', max_length=50)),
                ('verification_status', models.CharField(default='UNVERIFIED', max_length=50)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question_key')},
            },
        ),
    ]
