# Generated by Django 4.2.30 on 2026-08-01 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_enabled', models.BooleanField(default=False)),
                ('require_review_before_submit', models.BooleanField(default=True)),
                ('daily_application_limit', models.IntegerField(default=10)),
                ('weekly_application_limit', models.IntegerField(default=50)),
                ('minimum_match_score', models.IntegerField(default=75)),
                ('allowed_application_modes', models.JSONField(default=list, help_text='List of allowed platform capabilities (e.g. AUTHORIZED_API_APPLY)')),
                ('global_pause', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('REVIEW_REQUIRED', 'Review Required'), ('READY_TO_SUBMIT', 'Ready to Submit'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('APPLICATION_FAILED', 'Application Failed'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('FINAL_ROUND', 'Final Round'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('UNKNOWN', 'Unknown')], default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='PolicyDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50)),
                ('reason_codes', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_decisions', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='applications.automationpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('actor', models.CharField(default='SYSTEM', max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_fingerprint', models.CharField(max_length=255)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='VALID', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='applications.application')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
