# Generated by Django 4.2.30 on 2026-08-01 11:26

from django.db import migrations


def migrate_legacy_statuses(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    # Update 'Saved' -> 'DRAFT'
    Application.objects.filter(status='Saved').update(status='DRAFT')
    # Update 'Applied' -> 'SUBMITTED'
    Application.objects.filter(status='Applied').update(status='SUBMITTED')

def reverse_migrate(apps, schema_editor):
    # It is lossy to reverse, but we could try reverting if needed.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_automationpolicy_alter_application_status_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_statuses, reverse_migrate),
    ]
