# Generated by Django 4.2.30 on 2026-08-01 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0003_migrate_legacy_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('raw_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('status', models.CharField(default='DETECTED', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sessions', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormSessionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('field_key', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.formsession')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedApplicationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_field_id', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('name_attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('input_type', models.CharField(blank=True, max_length=100, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('normalized_key', models.CharField(default='UNKNOWN', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('proposed_value', models.TextField(blank=True, null=True)),
                ('resolution_status', models.CharField(default='PENDING', max_length=50)),
                ('answer_source', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_review', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applications.detectedapplicationform')),
            ],
        ),
        migrations.AddField(
            model_name='detectedapplicationform',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detected_form', to='applications.formsession'),
        ),
    ]
