# Generated by Django 4.2.30 on 2026-08-01 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0004_detectedapplicationform_formsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_fingerprint', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=100)),
                ('application_mode', models.CharField(max_length=100)),
                ('execution_status', models.CharField(default='CREATED', max_length=50)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='applications.application')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.applicationapproval')),
                ('policy_decision_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.policydecision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('external_application_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_requisition_id', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmation_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('confirmation_text_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('execution_mode', models.CharField(max_length=100)),
                ('receipt_source', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='applications.application')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='applications.applicationexecution')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=50)),
                ('execution_mode', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_metadata', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='applications.applicationexecution')),
            ],
        ),
    ]
