# Generated by Django 4.2.30 on 2026-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationexecution_submissionreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsession',
            name='provider_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='formsession',
            name='provider_variant',
            field=models.CharField(blank=True, help_text='Specific ATS variant/version detected', max_length=100, null=True),
        ),
    ]
