# Generated by Django 4.2.30 on 2026-08-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_formsession_provider_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREPARING', 'Preparing'), ('REVIEW_REQUIRED', 'Review Required'), ('READY_TO_SUBMIT', 'Ready to Submit'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('APPLICATION_FAILED', 'Application Failed'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('FINAL_ROUND', 'Final Round'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('UNKNOWN', 'Unknown')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
