# Generated by Django 4.2.30 on 2026-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('portal_type', models.CharField(default='Custom', max_length=50)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
