# Generated by Django 4.2.30 on 2026-08-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('minimum_experience', models.IntegerField(blank=True, null=True)),
                ('education_requirements', models.JSONField(default=list)),
                ('responsibilities', models.JSONField(default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements_norm', to='jobs.job')),
            ],
        ),
    ]
