# Generated by Django 4.2.30 on 2026-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_application_url_job_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='portal_type',
        ),
        migrations.AddField(
            model_name='job',
            name='application_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote_worldwide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='Custom', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='sponsorship_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='work_authorization_required',
            field=models.BooleanField(default=True),
        ),
    ]
