# Generated by Django 4.2.30 on 2026-08-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_portal_type_job_application_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='canonical_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Normalized identity for deduplication', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='JobSourceOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='jobs.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobsourceoccurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('source_job_id__isnull', False), models.Q(('source_job_id', ''), _negated=True)), fields=('source', 'source_job_id'), name='unique_source_job_id'),
        ),
    ]
