# Generated by Django 4.2.30 on 2026-08-09 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerOutcomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_hash', models.CharField(max_length=64, unique=True)),
                ('funnel_metrics', models.JSONField(default=dict)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('comparison_groups', models.JSONField(default=dict)),
                ('recommendation_inputs', models.JSONField(default=dict)),
                ('confidence', models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerOutcomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_state', models.CharField(choices=[('APPLIED', 'Applied'), ('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('FINAL_ROUND', 'Final Round'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('NO_RESPONSE', 'No Response'), ('UNKNOWN', 'Unknown')], max_length=50)),
                ('source_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_source', models.CharField(choices=[('SYSTEM_CONFIRMED', 'System Confirmed'), ('USER_CONFIRMED', 'User Confirmed'), ('PROVIDER_CONFIRMED', 'Provider Confirmed'), ('INFERRED', 'Inferred'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_id', models.IntegerField(blank=True, null=True)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('resume_version_id', models.IntegerField(blank=True, null=True)),
                ('tailoring_version_id', models.IntegerField(blank=True, null=True)),
                ('job_match_score', models.IntegerField(blank=True, null=True)),
                ('target_role', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('source_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.CharField(choices=[('VERY_LOW', 'Very Low'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], default='LOW', max_length=50)),
                ('verification_status', models.CharField(default='UNVERIFIED', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'normalized_state'], name='career_outc_user_id_dc7ce3_idx'), models.Index(fields=['resume_version_id'], name='career_outc_resume__c8cbee_idx'), models.Index(fields=['application_id'], name='career_outc_applica_3a4ec9_idx')],
            },
        ),
    ]
