# Generated by Django 4.2.30 on 2026-08-10 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('career_outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careeroutcomerecord',
            name='detected_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='careeroutcomerecord',
            name='normalized_state',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SUBMITTED', 'Submitted'), ('SCREENING', 'Screening'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('FINAL_ROUND', 'Final Round'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('NO_RESPONSE', 'No Response'), ('UNKNOWN', 'Unknown')], db_index=True, max_length=50),
        ),
    ]
