# Generated by Django 4.2.30 on 2026-08-02 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_repository_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('repository_url', models.URLField()),
                ('homepage_url', models.URLField(blank=True, null=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('visibility', models.CharField(default='public', max_length=50)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at_external', models.DateTimeField(blank=True, null=True)),
                ('updated_at_external', models.DateTimeField(blank=True, null=True)),
                ('pushed_at_external', models.DateTimeField(blank=True, null=True)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('watchers', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('primary_language', models.CharField(blank=True, max_length=100, null=True)),
                ('repository_topics', models.JSONField(blank=True, default=list)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('raw_metadata_snapshot', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_user_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('github_username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='PENDING', max_length=50)),
                ('sync_error_code', models.CharField(blank=True, max_length=50)),
                ('sync_error_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('_encrypted_access_token', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_url', models.URLField()),
                ('normalized_url', models.URLField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_status', models.CharField(default='PENDING', max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('repository_url', models.URLField(blank=True, null=True)),
                ('live_demo_url', models.URLField(blank=True, null=True)),
                ('technologies_detected', models.JSONField(blank=True, default=list)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('first_observed_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='evidence.portfolioconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GitHubSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repositories_discovered', models.IntegerField(default=0)),
                ('repositories_updated', models.IntegerField(default=0)),
                ('repositories_failed', models.IntegerField(default=0)),
                ('rate_limit_remaining', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='evidence.githubconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_sync_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('evidence_type', models.CharField(max_length=100)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('evidence_summary', models.TextField(blank=True)),
                ('confidence', models.CharField(default='MEDIUM', max_length=50)),
                ('status', models.CharField(default='DETECTED', max_length=50)),
                ('first_observed_at', models.DateTimeField(auto_now_add=True)),
                ('last_observed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='evidence.portfolioproject')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='evidence.candidaterepository')),
                ('skill_taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='learning.skilltaxonomy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidaterepository',
            name='github_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='evidence.githubconnection'),
        ),
        migrations.AddField(
            model_name='candidaterepository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to=settings.AUTH_USER_MODEL),
        ),
    ]
