# Generated by Django 4.2.30 on 2026-08-01 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('EXTRACTING', 'Extracting'), ('PARSING', 'Parsing'), ('REVIEW_REQUIRED', 'Review Required'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('parsing_error', models.TextField(blank=True)),
                ('parsed_text', models.TextField(blank=True)),
                ('health_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
