# Generated by Django 4.2.30 on 2026-08-01 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
                ('structured_content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW_REQUIRED', 'Review Required'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='health_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TailoringChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50)),
                ('original_text', models.TextField(blank=True)),
                ('proposed_text', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('SUPPORTED', 'Supported'), ('SUPPORTED_REPHRASE', 'Supported Rephrase'), ('AMBIGUOUS', 'Ambiguous'), ('UNSUPPORTED', 'Unsupported')], max_length=20)),
                ('user_decision', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], default='PENDING', max_length=20)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='resumes.resumeversion')),
            ],
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='source_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='target_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('GENERAL', 'General'), ('JOB_SPECIFIC', 'Job Specific')], max_length=20)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('calculation_version', models.CharField(max_length=50)),
                ('structured_results', models.JSONField(default=dict)),
                ('status', models.CharField(default='COMPLETE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
