# Generated by Django 4.2.30 on 2026-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeversion_alter_resume_ats_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeversion',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked versions cannot be modified, preserving historical integrity.'),
        ),
    ]
