# Generated by Django 4.2.30 on 2026-08-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '__first__'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='source',
            field=models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='certification',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='source',
            field=models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='education',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='source',
            field=models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='experience',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='career_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='source',
            field=models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='source',
            field=models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='skill',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('sponsorship_required', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_authorizations', to='profiles.profile')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.profile')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(blank=True, max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50)),
                ('preferred_roles', models.CharField(blank=True, max_length=255)),
                ('preferred_locations', models.CharField(blank=True, max_length=255)),
                ('preferred_industries', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('remote_preference', models.CharField(blank=True, max_length=50)),
                ('expected_compensation_min', models.IntegerField(blank=True, null=True)),
                ('expected_compensation_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('notice_period', models.CharField(blank=True, max_length=50)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('relocation_willingness', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='profiles.profile')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('USER_VERIFIED', 'User Verified'), ('RESUME_IMPORTED', 'Resume Imported'), ('EXTERNAL_IMPORTED', 'External Imported'), ('AI_INFERRED', 'AI Inferred')], default='USER_VERIFIED', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='VERIFIED', max_length=50)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profiles.profile')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resume')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
