# backend/applications/constants.py

class ExecutionStatus:
    CREATED = 'CREATED'
    VALIDATING = 'VALIDATING'
    AWAITING_USER = 'AWAITING_USER'
    READY = 'READY'
    EXECUTING = 'EXECUTING'
    VERIFYING = 'VERIFYING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    BLOCKED = 'BLOCKED'
    CANCELLED = 'CANCELLED'
    UNKNOWN_RESULT = 'UNKNOWN_RESULT'

class ExecutionMode:
    MANUAL_HANDOFF = 'MANUAL_HANDOFF'
    ASSISTED_USER_SUBMISSION = 'ASSISTED_USER_SUBMISSION'
    USER_CONFIRMED_BROWSER_SUBMISSION = 'USER_CONFIRMED_BROWSER_SUBMISSION'
    AUTHORIZED_API_SUBMISSION = 'AUTHORIZED_API_SUBMISSION'
    BLOCKED = 'BLOCKED'

class ReceiptSource:
    PROVIDER_API = 'PROVIDER_API'
    CONFIRMATION_PAGE = 'CONFIRMATION_PAGE'
    USER_CONFIRMED = 'USER_CONFIRMED'
    PROVIDER_CALLBACK = 'PROVIDER_CALLBACK'

class ExecutionError:
    POLICY_BLOCKED = 'POLICY_BLOCKED'
    GLOBAL_PAUSE = 'GLOBAL_PAUSE'
    PROVIDER_BLOCKED = 'PROVIDER_BLOCKED'
    UNSUPPORTED_MODE = 'UNSUPPORTED_MODE'
    STALE_APPROVAL = 'STALE_APPROVAL'
    STALE_FORM = 'STALE_FORM'
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD'
    CONSENT_REQUIRED = 'CONSENT_REQUIRED'
    CAPTCHA_REQUIRED = 'CAPTCHA_REQUIRED'
    AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED'
    EXECUTION_ALREADY_ACTIVE = 'EXECUTION_ALREADY_ACTIVE'
    DUPLICATE_APPLICATION = 'DUPLICATE_APPLICATION'
    DAILY_LIMIT_REACHED = 'DAILY_LIMIT_REACHED'
    WEEKLY_LIMIT_REACHED = 'WEEKLY_LIMIT_REACHED'
    NETWORK_FAILURE = 'NETWORK_FAILURE'
    PROVIDER_ERROR = 'PROVIDER_ERROR'
    VERIFICATION_FAILED = 'VERIFICATION_FAILED'
    UNKNOWN_PROVIDER_RESULT = 'UNKNOWN_PROVIDER_RESULT'
